[tool.poetry]
name = "beat-func"
version = "0.1.0"
description = ""
authors = ["dhsavell <dhsavell05@gmail.com>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.7"
beatmachine = {version = "==2.2.0-alpha.1", allow-prereleases = true}
fastapi = "^0.44.0"
uvicorn = "^0.10.8"
python-multipart = "^0.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
