[tool.poetry]
name = "beat-func"
version = "0.1.0"
description = ""
authors = ["dhsavell <dhsavell05@gmail.com>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.7"
beatmachine = "^3.0.0"
fastapi = "^0.44.0"
uvicorn = "^0.10.8"
python-multipart = "^0.0.5"
youtube_dl = "^2020.1.24"
mutagen = "^1.43.0"
xxhash = "^1.4.3"
cachetools = "^4.1.0"

[tool.poetry.dev-dependencies]
rope = "^0.14.0"
black = {version = "^18.3-alpha.0", allow-prereleases = true}
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
