name: Google Cloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: exelban/gcloud@master
      env:
        PROJECT_ID: ${{secrets.PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.APPLICATION_CREDENTIALS}}
      with:
        args: builds submit --tag gcr.io/beat-machine-244519/beatfunc

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: exelban/gcloud@master
      env:
        PROJECT_ID: ${{secrets.PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.APPLICATION_CREDENTIALS}}
      with:
        args: beta run deploy --quiet --image gcr.io/beat-machine-244519/beatfunc --platform managed
