name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libopenblas-dev portaudio19-dev fftw-dev ffmpeg git build-essential curl
          version: 1.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root --no-interaction --no-ansi -E simple
      - name: Lint
        run: |
          poetry run black --check .
          poetry run isort --check .
      - name: Test
        run: |
          poetry run pytest
